# Get Data

## Import Libraries

### Built-in Libraries

### External Libraries

In [2]:
import geopandas as gpd

## 311 Service Requests from 2010 to Present

### About

| Key | Value |
| --- | ----- |
| URL | https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9 |
| Description | All 311 Service Requests from 2010 to present. |
| Updated | 2023-02-13 |
| Views | 440K+ |
| Data Provided by | [311](https://data.cityofnewyork.us/browse?Dataset-Information_Agency=311), DoITT |
| Category | [Social Services](https://data.cityofnewyork.us/browse?category=Social+Services) |
| API Docs | https://dev.socrata.com/foundry/data.cityofnewyork.us/erm2-nwe9 |
| API Endpoints | [JSON](https://data.cityofnewyork.us/resource/erm2-nwe9.json)<br>[GeoJSON](https://data.cityofnewyork.us/resource/erm2-nwe9.geojson)<br>[CSV](https://data.cityofnewyork.us/resource/erm2-nwe9.csv) |
| `complaint_type` | Sewer |
| `descriptor` | Street Flooding (SJ) |

### Define Variables

In [10]:
NYC_OPEN_DATA_311_API_JSON = 'https://data.cityofnewyork.us/resource/erm2-nwe9.json?descriptor=Street%20Flooding%20(SJ)'
NYC_OPEN_DATA_311_API_GEOJSON = 'https://data.cityofnewyork.us/resource/erm2-nwe9.geojson?descriptor=Street%20Flooding%20(SJ)'
NYC_OPEN_DATA_311_API_CSV = 'https://data.cityofnewyork.us/resource/erm2-nwe9.csv?descriptor=Street Flooding (SJ)'

### Download 311 Service Complaints for `Street Flooding (SJ)`

In [12]:
street_flooding_gdf = gpd.read_file(NYC_OPEN_DATA_311_API_GEOJSON, driver='GeoJSON')

### Preview Street Flooding Data

In [16]:
print(f'Total Observations: {len(street_flooding_gdf)}')

Total Observations: 1000

In [14]:
street_flooding_gdf.head(10)

,location_state,facility_type,intersection_street_2,city,location_zip,park_borough,latitude,road_ramp,created_date,agency,...,resolution_description,community_board,resolution_action_updated_date,intersection_street_1,closed_date,vehicle_type,cross_street_1,borough,landmark,geometry
0,,NaN,NaN,BROOKLYN,,BROOKLYN,40.59319580218309,NaN,2023-02-11 03:56:00,DEP,...,NaN,13 BROOKLYN,NaT,NaN,NaT,NaN,27 AVE,BROOKLYN,NaN,POINT (-73.98458 40.59320)
1,,NaN,NaN,BROOKLYN,,BROOKLYN,40.70500111908766,NaN,2023-02-10 17:59:00,DEP,...,The Department of Environment Protection inspe...,01 BROOKLYN,2023-02-11 09:00:00,NaN,2023-02-11 09:00:00,NaN,THAMES ST,BROOKLYN,NaN,POINT (-73.93062 40.70500)
2,,NaN,NaN,BROOKLYN,,BROOKLYN,40.63036236617889,NaN,2023-02-10 16:14:00,DEP,...,The Department of Environmental Protection det...,18 BROOKLYN,2023-02-11 15:45:00,NaN,2023-02-11 15:45:00,NaN,AVENUE N,BROOKLYN,NaN,POINT (-73.89755 40.63036)
3,,NaN,UTOPIA PARKWAY,QUEENS,,QUEENS,40.73267668386468,NaN,2023-02-10 16:05:00,DEP,...,NaN,08 QUEENS,NaT,69 AVENUE,NaT,NaN,NaN,QUEENS,NaN,POINT (-73.79334 40.73268)
4,,NaN,NEWTON STREET,BROOKLYN,,BROOKLYN,40.72013922147923,NaN,2023-02-10 14:02:00,DEP,...,The Department of Environmental Protection has...,01 BROOKLYN,2023-02-11 08:35:00,MANHATTAN AVENUE,2023-02-11 08:35:00,NaN,NaN,BROOKLYN,NaN,POINT (-73.94758 40.72014)
5,,NaN,NaN,NEW YORK,,MANHATTAN,40.77509150824827,NaN,2023-02-09 16:47:00,DEP,...,The Department of Environment Protection inspe...,08 MANHATTAN,2023-02-09 18:50:00,NaN,2023-02-09 18:50:00,NaN,2 AVE,MANHATTAN,NaN,POINT (-73.95318 40.77509)
6,,NaN,NaN,BRONX,,BRONX,40.84382003421587,NaN,2023-02-09 14:50:00,DEP,...,The Department of Environmental Protection has...,10 BRONX,2023-02-09 17:15:00,NaN,2023-02-09 17:15:00,NaN,DWIGHT PL,BRONX,NaN,POINT (-73.82346 40.84382)
7,,NaN,NaN,BROOKLYN,,BROOKLYN,40.68038533846951,NaN,2023-02-09 13:08:00,DEP,...,The Department of Environmental Protection has...,03 BROOKLYN,2023-02-09 13:08:00,NaN,2023-02-09 13:08:00,NaN,STUYVESANT AVE,BROOKLYN,NaN,POINT (-73.92949 40.68039)
8,,NaN,NaN,BROOKLYN,,BROOKLYN,40.61687850569994,NaN,2023-02-07 18:11:00,DEP,...,The Department of Environmental Protection ins...,18 BROOKLYN,2023-02-08 09:00:00,NaN,2023-02-08 09:00:00,NaN,E 37 ST,BROOKLYN,NaN,POINT (-73.93767 40.61688)
9,,NaN,13 AVENUE,BROOKLYN,,BROOKLYN,40.635581624381615,NaN,2023-02-07 16:23:00,DEP,...,The Department of Environmental Protection has...,12 BROOKLYN,2023-02-07 16:40:00,48 STREET,2023-02-07 16:40:00,NaN,NaN,BROOKLYN,NaN,POINT (-73.99154 40.63558)